#!/bin/bash -l

#$ -pe omp 6
#$ -P ivc-ml
#$ -l h_rt=120:00:00
#$ -l gpus=2
#$ -l gpu_c=6.0
#$ -N daformer
#$ -j y
#$ -m ea

export OMP_NUM_THREADS=2
export TF_NUM_INTEROP_THREADS=2
export TF_NUM_INTRAOP_THREADS=1

module load miniconda
conda activate daformer

cd /projectnb/ivc-ml/dbash/code/DAFormer

# python tools/convert_datasets/gta.py /projectnb/ivc-ml/dbash/data/gta/ --nproc 3 \
#  -o /projectnb/ivc-ml/dbash/daformer/data/gta
# LD_LIBRARY_PATH=/projectnb/ivc-ml/dbash/.conda/envs/daformer/lib python run_experiments.py --config configs/daformer/gta2cs_uda_warm_fdthings_rcs_croppl_a999_daformer_mitb5_s0.py

LD_LIBRARY_PATH=/projectnb/ivc-ml/dbash/.conda/envs/daformer/lib bash test.sh  work_dirs/local-basic/220218_1349_gta2cs_uda_warm_fdthings_rcs_croppl_a999_daformer_mitb5_s0_f358c
